### PR TITLE
Change examples from FFI::Platypus::Declare to FFI::Platypus

### PR DESCRIPTION
**Pull request by oylenshpeegul**
The docs for FFI::Platypus::Declare say it is "discouraged", so I re-worked the examples to use the OO interface instead.

### CODE REVIEW

**Comment by plicease** [comment]
Great, thanks.

**Comment by plicease** [comment]
@oylenshpeegul you didn't happen to be at DCBPW on Saturday asking me questions about using Rust with FFI? :)

**Comment by oylenshpeegul** [comment]
Yup, that's me! I was playing with your examples anyway and when I read the docs, it said to use the OO interface instead. So I did. It was kind of instructive to do things twice!

**Comment by plicease** [comment]
Cool.  Btw- I was working at one point on merging this into Platypus core, (wip PR here: https://github.com/nwellnhof/perl-commonmark/pull/9#issuecomment-480799751 ) but I probably won't be doing that as it makes it harder to experiment with this module.  There are a couple of things from that branch that should be ported back into this dist though.  For example I want to lean more heavily on cargo for bundling rust code with an FFI module, (and use `FFI::Build` instead of `Module::Build::FFI`) I'll see if I can do some of those things this week.

**Comment by plicease** [comment]
sorry fixed the URL above, cut-and-paste fail!

**Comment by oylenshpeegul** [comment]
Yes, I had been playing with it in my cargo directory, with the Perl code in a perl subdirectory. Then I'd build the Rust part with cargo instead of rustc and use FindBin to load the appropriate .so from Perl. For example,

```perl
use FindBin;

my $debug = shift;

my $libpoints = $debug ?
	"$FindBin::Bin/../target/debug/deps/libpoints.so" :
	"$FindBin::Bin/../target/release/libpoints.so";
```

**Pull request merged**
